### ISSUE TITLE
chore(refactor): move all terraform code into ./terraform

### ISSUE THREAD

**Issue by mvanholsteijn** [tiborhercz/AWScissors#3]
customarily, all tf templates are organized in the ./terraform directory

**Comment by tiborhercz** [comment]
This should seem like a fairly simply task, but we should make sure the Lambda packer still functions.
The Lambda packer uses `path.module`

```
module "go_lambda_packer_event_parser" {
  source      = "./modules/go-lambda-packer"
  source_path = "${path.module}/lambda/event-parser"
  output_path = "${path.module}/event-parser.zip"
}
```

[event-parser-lambda.tf](https://github.com/tiborhercz/AWScissors/blob/main/event-parser-lambda.tf)

**Comment by tiborhercz** [comment]
Done: https://github.com/tiborhercz/AWScissors/pull/7
